### ISSUE TITLE
How to test client?

### ISSUE THREAD

**Issue by darakim** [YassineFadhlaoui/Real-Time-Video-Streaming#2]
How to test client?
Start server and start the client application, visit http://localhost:8000/
![image](https://user-images.githubusercontent.com/27200564/36091320-c0405ebc-1026-11e8-9d4b-1e627ed91e69.png)

I want test rtsp stream in browser.

**Comment by YassineFadhlaoui** [comment]
Hallo @darakim. Try to visit `http://localhost:8000/app/#/Stream` instead of `http://localhost:8000/`

**Comment by darakim** [comment]
Oh! Thank you so much your answer. 
Is it right that click 'GET YOU HOME' button?
I have a few questions, if you know please answer.

1. Once a video has been played, it can not be played again.
2. I want to use ip camera to play video playback. Is it possible play multi camera playback?
3. How to play and pause?
4. I want to use it in an environment that does not have an Internet connection.
5. How to change client port?

**Comment by YassineFadhlaoui** [comment]
Hallo again @darakim , yes you can directly click 'GET YOU HOME'. I will try to answer your questions with my humble knowledge:
1. Once a video has been played it cannot be `paused or played` again because I want it to be real time so the traffic coming from the IP camera is displayed` in real time`. 
2. `multi-camera` playback (I did not try it)
3. -
4. Yes you can use it in an environment without `an internet connection`
5. to change the client consult `Real-Time-Video-Streaming/client/app/js/connect.js` and `Real-Time-Video-Streaming/server/streamserver.js` 

Hope it helps
